language: elixir

notifications:
  email: false

env:
  - MIX_ENV=test

elixir:
  - 1.3.2
  - 1.2.6

otp_release:
  - 18.0
  - 19.0

matrix:
  exclude:
    - elixir: 1.3.2
      otp_release: 18.0
    - elixir: 1.2.6
      otp_release: 19.0

branches:
  only:
    - master
    - develop

script:
  - mix test
  - mix credo --strict
  - mix coveralls

after_success:
  - mix coveralls.travis
